---
title: "Graphs and tables for OSC NY income tax project"
author: "Don Boyd"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    df_print: paged
    fig_height: 6
    fig_width: 8
    toc: yes
  html_document:
    toc: yes
    df_print: paged
editor_options:
  chunk_output_type: inline
---

<!-- 
  html_document:
    fig_height: 6
    fig_width: 8
    toc: yes
    toc_depth: 5
editor_options:
  chunk_output_type: console or inline    
    
-->



```{r setup, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



```{r notes, include=FALSE}
# It can be hard to get tables to work properly. It seems like it is best to have chunk output inline.

```


```{r libs, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# source(here::here("includes", "libraries.r"))
library(tidyverse)
library(readxl)
library(btools)
library(bdata)
library(DT)
library(microweight)
library(knitr)
devtools::session_info()

```


# SOI Historical Table 2

## Observations


## Descriptive statistics

```{r load_data, rows.print = 11, include=FALSE}
# 0 = No AGI Stub
# 1 = ‘Under $1’
# 2 = '$1 under $10,000'
# 3 = '$10,000 under $25,000'
# 4 = '$25,000 under $50,000'
# 5 = '$50,000 under $75,000'
# 6 = '$75,000 under $100,000'
# 7 = '$100,000 under $200,000'
# 8 = ‘$200,000 under $500,000’
# 9 = ‘$500,000 under $1,000,000’
# 10 = ‘$1,000,000 or more’

# A01000	Net capital gain (less loss) amount

xlfile <- 'Boyd OSC analysis(4).xlsx'

xwalk <- read_excel(here::here('ignore', xlfile), sheet='2018dictionary')
xwalk
ht(xwalk)

stubs <- read_excel(here::here('ignore', 'Boyd OSC analysis(4).xlsx'), 
                    sheet='agistubs',
                    range='A3:B14') %>%
              mutate(agi_stub=as.integer(agi_stub))
stubs

ht2 <- readRDS(here::here('data', 'soi', 'ht2.rds'))
glimpse(ht2)

ht2a <- ht2  %>%
  filter(stabbr != "PR") %>%  # PR showed up in 2018
  left_join(stubs,
            by='agi_stub')
count(ht2a, agi_stub, aginame)
glimpse(ht2a)

# A18425 State and local income taxes amount
# n18425

# now make a long file with labels
ht2long <- ht2a %>%
  pivot_longer(cols = -c(year, stabbr, agi_stub, aginame)) %>%
  left_join(xwalk %>% 
              select(name=variable, description) %>%
              mutate(name=str_to_lower(name)),
            by = "name")

n1 <- ht2long %>%
  filter(name=="n1") %>% 
  select(year, stabbr, agi_stub, n1=value)

h2n1 <- ht2long %>%
  left_join(n1, by = c("year", "stabbr", "agi_stub")) %>%
  mutate(avgvalue=ifelse(name %in% c("n1", "mars1", "mars2"), 
                         value / n1 * 100,
                         value / n1 * 1000))


h2n1 %>% filter(stabbr=="CA", agi_stub==0, name=="mars1")

```


### Percent change from year to year, selected variables: NY, US, and selected large states
```{r}
varstub_pch <- function(var, stub, sts){
  df <- h2n1 %>%
    filter(name==var, agi_stub==stub, stabbr %in% sts) %>%
    group_by(stabbr, agi_stub) %>%
    arrange(year) %>%
    mutate(pch=value / value[match(year - 1, year)] * 100 - 100) %>%
    filter(!is.na(pch)) %>%
    select(-value, -n1) %>%
    pivot_wider(names_from=year, values_from=pch) %>%
    mutate(stabbr=factor(stabbr, levels=sts)) %>%
    arrange(stabbr)
  df
}


# define states of interest
sts <- c("NY", "US", "CA", "CT", "FL", "TX")

# varstub_pch("n1", 0, sts) %>% kable(digits=1)

```


#### % change in number of returns: all returns and selected income groups
```{r}

varstub_pch("n1", 0, sts) %>% kable(digits=1)

```



### 2016 to 2018
#### Raw % change in tax



```{r explore, eval=FALSE}

tmp <- ht2 %>%
  filter(stabbr != "PR") %>%  # PR showed up in 2018
  select(year, stabbr, agi_stub, a18425, n18425) %>%
  mutate(agi_stub = as.factor(agi_stub),
         avg18425 = a18425 / n18425 * 1000) %>%
  # filter(year==2016)
  group_by(stabbr, agi_stub) %>%
  # mutate(n = n())
  mutate(iavg18425=avg18425 / avg18425[year==2016] * 100) %>%
  ungroup

tmp %>%
  filter(agi_stub %in% 7:10) %>%
  filter(stabbr %in% c("US", "NY", "FL", "CA", "AL", "MS", "NM", "MA", "NJ", "NH")) %>%
  ggplot(aes(year, iavg18425, colour=agi_stub)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 100) +
  facet_wrap(~stabbr, scales = "fixed", ncol=5)


ht2 %>%
  select(year, stabbr, agi_stub, a18425, n18425) %>%
  mutate(agi_stub = as.factor(agi_stub),
         avg18425 = a18425 / n18425 * 1000) %>%
  group_by(stabbr, agi_stub) %>%
  mutate(davg18425=avg18425 - avg18425[year==2016]) %>%
  ungroup %>%
  filter(agi_stub %in% 7:10) %>%
  filter(stabbr %in% c("US", "NY", "FL", "CA", "AL", "MS", "NM", "MA", "NJ", "NH", "CT")) %>%
  ggplot(aes(year, davg18425 / 1e3, colour=agi_stub)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(breaks=seq(-100, 100, 10)) +
  geom_hline(yintercept = 0) +
  facet_wrap(~stabbr, scales = "fixed", ncol=4)

ht2 %>%
  select(year, stabbr, agi_stub, a18425, n18425) %>%
  mutate(agi_stub = as.factor(agi_stub),
         avg18425 = a18425 / n18425 * 1000) %>%
  group_by(stabbr, agi_stub) %>%
  # mutate(i18425=n18425 / n18425[year==2016] * 100) %>%
  mutate(i18425=a18425 / a18425[year==2016] * 100) %>%
  ungroup %>%
  filter(agi_stub %in% 7:10) %>%
  filter(stabbr %in% c("US", "NY", "FL", "CA", "AL", "MS", "NM", "MA", "NJ", "NH", "CT")) %>%
  ggplot(aes(year, i18425, colour=agi_stub)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(breaks=seq(-100, 200, 10)) +
  geom_hline(yintercept = 100) +
  facet_wrap(~stabbr, scales = "fixed", ncol=4)

ns(ht2)

ht2 %>%
  # select(year, stabbr, agi_stub, a18425, n18425, a01400, n01400) %>%
  mutate(agi_stub = as.factor(agi_stub),
         avg18425 = a18425 / n18425 * 1000) %>%
  group_by(stabbr, agi_stub) %>%
  # mutate(ivalue=n18425 / n18425[year==2016] * 100) %>%
  # mutate(ivalue=a18425 / a18425[year==2016] * 100) %>%
  # mutate(ivalue=avg18425 / avg18425[year==2016] * 100) %>%
  mutate(value = a00600 / n00600) %>%
  mutate(value = a01000) %>%
  mutate(ivalue=value / value[year==2016] * 100) %>% # a01400 taxable IRA distributions
  ungroup %>%
  filter(agi_stub %in% 7:10) %>%
  filter(stabbr %in% c("US", "NY", "FL", "CA", "AL", "MS", "NM", "MA", "NJ", "NH", "CT", "TX")) %>%
  ggplot(aes(year, ivalue, colour=agi_stub)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(breaks=seq(-100, 200, 10)) + # , limits=c(50, 150)) +
  geom_hline(yintercept = 100) +
  facet_wrap(~stabbr, scales = "free", ncol=4)


```


## Descriptive statistics
### 2016 to 2018
#### Raw % change in tax
```{r}
# A10300	Total tax liability amount [11]
# get n, value, and averages for selected variables
vars <- c("")

ht2 %>%
  filter(year %in% 2016:2018,
         agi_stub == 0,
         !stabbr %in% c("OA", "PR")) %>%
  select(year, stabbr, agi_stub, a10300) %>%
  mutate(year=paste0("y", year)) %>%
  pivot_wider(names_from = year, values_from=a10300) %>%
  mutate(p1617=y2017 / y2016 * 100 - 100,
         p1718 =y2018 / y2017 * 100 - 100) %>%
  arrange(p1718) %>%
  kable(format='rst', digits=c(rep(0, 5), 1, 1))
  

```



## 2017
```{r mshare, rows.print = 11}
ht2_all <- readRDS(here::here("data", "soi", "ht2.rds"))

mshare <- ht2_all %>%
  filter(year==2017) %>%
  select(stabbr, agi_stub, n1) %>%
  filter(agi_stub %in% c(0, 8:10)) %>%
  group_by(stabbr) %>%
  mutate(pct=n1 / n1[agi_stub == 0],
         group=paste0("grp", str_pad(agi_stub, width=2, side="left", pad="0"))) %>%
  select(-n1, -agi_stub) %>%
  pivot_wider(names_from = group, values_from = pct) %>%
  ungroup %>%
  mutate(higroup=grp08 + grp09 + grp10,
         index10=grp10 / grp10[stabbr == "US"] * 100,
         indexhi=higroup / higroup[stabbr == "US"] * 100)

mshare %>%
  arrange(-index10) %>%
  datatable

```


```{r millionaires, rows.print=11}

mdf <- ht2_all %>%
  filter(year==2017) %>%
  group_by(stabbr) %>%
  mutate(mpct = n1 / n1[agi_stub == 0] * 100) %>%
  ungroup %>%
  filter(agi_stub==10) %>%
  mutate(avgagi_m=a00100 / n1 / 1e3,
         marpct=mars2 / n1 * 100,
         avgkids=numdep / n1,
         oldpct = elderly / n1 * 100,
         wagepct = a00200 / a00100 * 100,
         cgpct = a01000 / a00100 * 100,
         businc = a00900,
         partinc = a26270,
         busincpct=businc / a00100 * 100,
         partincpct=partinc / a00100 * 100,
         retinc=a01400 + a01700 + a02500,
         retincpct=retinc / a00100 * 100,
         otherpct=100 - wagepct - cgpct - busincpct - partincpct - retincpct) %>%
  select(stabbr, n1, mpct, avgagi_m, marpct, avgkids, oldpct, wagepct, cgpct, busincpct, partincpct, retincpct, otherpct)

mdf %>%
  filter(!stabbr %in% c("OA", "DC")) %>%
  mutate(rank=rank(-mpct)) %>%
  mutate(across(c(avgkids, contains("pct"), -mpct), function(x) round(x, 1))) %>%
  mutate(across(avgagi_m, function(x) round(x, 2))) %>%
  mutate(across(mpct, function(x) round(x, 2))) %>%
  arrange(rank) %>%
  filter(row_number() %in% 1:10 | stabbr=="US") %>%
  select(stabbr, n1, mpct, rank, everything()) %>%
  datatable(options = list(pageLength = 11))
  


```

## Time series

```{r ts}
data(package="bdata")
glimpse(soiall)
count(soiall, year) # 2004-2013
count(soiall, vname)
count(soiall, incgrp)

count(soiall, year, incgrp)




ht2m_prior <- soiall %>%
  filter(year %in% 2004:2012) %>%
  filter(vname=="nret") %>%
  mutate(agi_stub=case_when(incgrp == "$1m+" ~ 10,
                            incgrp == "all" ~ 0,
                            TRUE ~ NA_real_)) %>%
  filter(agi_stub %in% c(0, 10)) %>%
  select(year, stabbr, agi_stub, n1=value)

ht2m_prior %>% filter(year==2012, stabbr=="US")
ht2_all %>% filter(year==2012, stabbr=="US", agi_stub %in% c(0, 10)) %>% select(year, stabbr, agi_stub, n1)
# year stabbr agi_stub n1
# 2012	US	0	145025450	
# 2012	US	10	392270
# year stabbr agi_stub n1
# 2012	US	0	145025450	
# 2012	US	10	392270	
  

ht2_all
glimpse(ht2_all)
ht2_all %>%
  bind_rows(ht2m_prior %>% filter(year %in% 2010:2011)) %>% # only 2 years with the $1m+ category
  select(year, stabbr, agi_stub, n1) %>%
  group_by(stabbr, year) %>%
  mutate(n1_all=n1[agi_stub==0]) %>%
  ungroup %>%
  filter(agi_stub==10) %>%
  mutate(mpct=n1 / n1_all * 100) %>%
  filter(stabbr %in% c("CT", "NY", "MA", "NJ", "CA", "FL", "TX")) %>%
  ggplot(aes(year, mpct, colour=stabbr)) +
  geom_line() +
  geom_point()

ht2_all %>%
  bind_rows(ht2m_prior %>% filter(year %in% 2010:2011)) %>% # only 2 years with the $1m+ category
  select(year, stabbr, agi_stub, n1) %>%
  group_by(stabbr, year) %>%
  mutate(n1_all=n1[agi_stub==0]) %>%
  ungroup %>%
  filter(agi_stub==10) %>%
  mutate(mpct=n1 / n1_all * 100) %>%
  filter(stabbr %in% c("CT", "NY", "MA", "NJ", "CA", "FL", "TX")) %>%
  ggplot(aes(year, n1, colour=stabbr)) +
  geom_line() +
  geom_point()


# something happened in FL, TX in 2016, 2017
ht2_all %>%
  bind_rows(ht2m_prior %>% filter(year %in% 2010:2011)) %>% # only 2 years with the $1m+ category
  select(year, stabbr, agi_stub, n1) %>%
  group_by(stabbr, year) %>%
  mutate(n1_all=n1[agi_stub==0]) %>%
  ungroup %>%
  filter(agi_stub==10) %>%
  group_by(stabbr) %>%
  mutate(im=n1 / n1[year==2010] * 100) %>%
  filter(stabbr %in% c("CT", "NY", "MA", "NJ", "CA", "FL", "TX")) %>%
  ggplot(aes(year, im, colour=stabbr)) +
  geom_line() +
  geom_point()

# share of m's
st <- "CA"

sts <- c("CA", "CT", "FL", "IL", "MA", "NJ", "NY", "TX", "WA")
ht2_all %>%
  bind_rows(ht2m_prior %>% filter(year %in% 2010:2011)) %>% # only 2 years with the $1m+ category
  filter(agi_stub %in% c(0, 10)) %>%
  select(year, stabbr, agi_stub, n1) %>%
  mutate(agi_stub=paste0("stub", str_pad(agi_stub, width=2, side="left", pad="0"))) %>%
  pivot_wider(values_from = n1, names_from = agi_stub) %>%
  mutate(stubres=stub00 - stub10) %>%
  group_by(year) %>%
  mutate(across(starts_with("stub"), function(x) x / x[stabbr=="US"] * 100)) %>%
  filter(stabbr %in% sts) %>%
  select(-stub00) %>%
  pivot_longer(starts_with("stub")) %>%
  group_by(name) %>%
  mutate(ivalue=value / value[year==2010] * 100) %>%
  ggplot(aes(year, ivalue, colour=name)) +
  geom_line() +
  geom_point() +
  facet_wrap(~stabbr, ncol = 3, scales="free")
  


```


